# Generated by Django 4.2.22 on 2025-06-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
